service: gemstash
image: itsterry/gemstash

servers:
  web:
    hosts:
      - 35.177.246.4

proxy:
  ssl: true
  host: gemstash.morsedigital.com
  app_port: 9292
  healthcheck:
    path: /health

registry:
  username: itsterry
  password:
    - KAMAL_REGISTRY_PASSWORD

# ssh:
#   user: gemstash

aliases:
  logs: app logs -f
  shell: app exec --interactive --reuse "bash"

volumes:
  - /var/www/gemstash:/data

env:
  clear:
    GEMSTASH_CACHE: /data/cache
    GEMSTASH_STORAGE: /data/storage
    GEMSTASH_UPSTREAM: https://rubygems.org
    GEMSTASH_DEPENDENCY_API_ENABLED: false

builder:
  arch: amd64
  # cache:
  #   type: registry
  #   options: mode=max
